//@version=4
study(title="Relative Effort Density Candles", shorttitle="REDC", format=format.price, overlay=true, scale=scale.right)
effortSrc = input(title='effor src', type=input.source, defval=close)
thresh = input(title='highlight threshold', type=input.float, defval=150, minval=0)
useStd = input(title='std used in effort', type=input.bool, defval=false)

range_min = useStd ? -400 : 0
range_max = thresh*3
var color C_BLACK = #000000
var color C_WHITE  = #FFFFFF
color c_density = color.from_gradient(effortSrc, range_min, range_max, C_WHITE, C_BLACK)
emphClr() => effortSrc > thresh ? color.orange : c_density
priceUp = close - open > 0
plotcandle(open, high, low, close, color = emphClr(), wickcolor=emphClr(), bordercolor=emphClr() )
plotshape(priceUp, style=shape.circle, color=color.green, size=size.tiny, location=location.belowbar, transp=80)
plotshape(not priceUp, style=shape.circle, color=color.red, size=size.tiny, location=location.belowbar, transp=80)