//@version=4
study(title="Relative Effort in Percent", format=format.price, resolution="", overlay=false)
period = input(title='avg period', type=input.integer, defval=25, minval=1)

// For each bar, tells how much effort it needed to move the price within (effort = vol/range)
// in percentage by comparing against average effort in the past given period length

// It's critical to choose a data source with reliable or preferable volume information

effort = volume/atr(1)
avgEffort = sma(effort, period)
percentEffort = effort/avgEffort*100

plot(percentEffort, color=#156A99, title="Percent Effort")
hline(50, color=#C0C0C0, linestyle=hline.style_solid)
hline(100, color=#C0C0C0)
hline(150, color=#C0C0C0, linestyle=hline.style_solid)